# serverless.yml

service: warframe-item-tracker

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  lambdaHashingVersion: 20201221

functions:
  general:
    handler: index.handler
    events:
      - http: 'ANY /'
      - http: 'ANY {proxy+}'
  userEvents:
    handler: index.handler
    events:
      - http: 'ANY /users/{proxy+}'
  apiEvents:
    handler: index.handler
    events:
      - http: 'ANY /api/{proxy+}'
