# serverless.yml

service: warframe-item-tracker

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  lambdaHashingVersion: 20201221

functions:
  general:
    handler: index.handler
    events:
      - http: 'ANY /'
      - http: 'ANY {proxy+}'
  userEvents:
    handler: index.handler
    events:
      - http: 'ANY /users/{proxy+}'
  apiEvents:
    handler: index.handler
    events:
      - http:
          path: api/items/
          method: get
          cors: true
      - http:
          path: api/items/track/{proxy+}
          method: get
          cors: true
      - http:
          path: api/items/untrack/{proxy+}
          method: get
          cors: true
      - http:
          path: api/items/{proxy+}
          method: get
          cors: true
      - http:
          path: api/watchlist/add/{proxy+}
          method: get
          cors: true
      - http:
          path: api/watchlist/remove/{proxy+}
          method: get
          cors: true
      - http:
          path: api/watchlist/list
          method: get
          cors: true
